name: Daily Stock Scan
on:
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # เปลี่ยนจาก v2 เป็น v4
      - name: Set up Python
        uses: actions/setup-python@v5 # เปลี่ยนจาก v2 เป็น v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install streamlit yfinance pandas altair numpy plotly gspread seaborn matplotlib oauth2client
      - name: Run script
        run: python App.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
